apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 927d5ffa-b3a2-477a-8dcc-1d8d6f845dc3
    run.googleapis.com/build-image-uri: asia-southeast1-docker.pkg.dev/cf-akasach/cloud-run-source-deploy/grpc-calculator
    run.googleapis.com/build-name: projects/321527618877/locations/global/builds/927d5ffa-b3a2-477a-8dcc-1d8d6f845dc3
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://grpc-calculator-321527618877.asia-southeast1.run.app","https://grpc-calculator-lcpia55i5q-as.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-southeast1
    run.googleapis.com/satisfiesPzs: 'true'
  name: grpc-calculator
  namespace: '321527618877'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 504.0.1
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: bkrcuqmewx
        run.googleapis.com/startupProbeType: Custom
    spec:
      containerConcurrency: 80
      containers:
      - image: asia-southeast1-docker.pkg.dev/cf-akasach/cloud-run-source-deploy/grpc-calculator@sha256:85f6bce6fc40d47a8029aab2e804461811dea257f761afb0f423569d2b3d16b8
        name: grpc-calculator-1
        ports:
        - containerPort: 8443
          name: h2c
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          grpc:
            port: 8443
            service: grpc.health.v1.Health
          periodSeconds: 240
          timeoutSeconds: 240
      serviceAccountName: 321527618877-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
